---
- name: Get undercloud admin password
  command: >
    awk -F= '$1 == "undercloud_admin_password" {print $2}'
    {{ working_dir }}/undercloud-passwords.conf
  register: undercloud_admin_password

- name: Copy stackrc to ansible host
  fetch:
    flat: true
    src: stackrc
    dest: "{{ local_working_dir }}/stackrc"

# we needs (and the previous task) in order to replace the
# `sudo hiera admin_password` with an actual password.
- name: Update admin password in local credentials file
  delegate_to: localhost
  lineinfile:
    dest: "{{ local_working_dir }}/stackrc"
    line: "export OS_PASSWORD={{ undercloud_admin_password.stdout }}"
    regexp: "OS_PASSWORD"

- block:
    - name: "Push baremetal instackenv.json"
      copy:
        src: "{{ baremetal_instackenv }}"
        dest: "{{ working_dir }}/instackenv.json"
    - name: "Push network-environment.yaml"
      copy:
        src: "{{ baremetal_network_environment }}"
        dest: "{{ working_dir }}/network-environment.yaml"
  when: undercloud_type == "baremetal"

- name: "Push baremetal nic-configs directory (if defined)"
  copy:
    src: "{{ baremetal_nic_configs }}"
    dest: "{{ working_dir }}"
  when: undercloud_type == "baremetal" and baremetal_nic_configs is defined

- name: Create undercloud post-install script
  template:
    src: "{{ undercloud_post_install_script }}"
    dest: "{{ working_dir }}/undercloud-post-install.sh"
    mode: 0755

- name: Prepare the undercloud for deploy
  shell: >
    {{ working_dir }}/undercloud-post-install.sh > {{ undercloud_post_install_log }} 2>&1
  when: step_install_undercloud

- name: allow traffic for the controller
  become: yes
  shell: >
        iptables -A BOOTSTACK_MASQ -s {{ network_isolation_ipv4_cidr }} ! -d {{ network_isolation_ipv4_cidr }} -j MASQUERADE -t nat;
        iptables-save > /etc/sysconfig/iptables;
  when: network_isolation
